server:
  servlet:
    context-path: /centreon-studio/rest
#  port: 8080

spring:
  jackson:
    serialization:
      indent-output: true      
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    git:
      mode: full