server:
  servlet:
    context-path: /centreon-studio/rest
#  port: 8080

spring:
#  profiles:
#    active: production
  datasource:
#      url: jdbc:h2:mem:~testdb
#      username: sa
#      password: 
      url: jdbc:mariadb://localhost:3306/centreon?rewriteBatchedStatements=true
      username: centreon_map
      password: centreon_map
#      url: ${dataBase.driverUrl}
#      username: ${dataBase.username}
#      password: ${dataBase.password}
      hikari:
        maximum-pool-size: 20
        minimum-idle: 5
  jackson:
    serialization:
      indent-output: true      
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    git:
      mode: full