spring:
  cloud:
    config:
      server:
        git:
          uri: file:/home/jwang/DEV/git/config-repo
          clone-on-start: false
#          uri: https://github.com/wangjulien/config-repo.git
#          search-paths:
#          username: 
#          password: #      label: master
       
          
