spring:
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/Dev/workspaces/cloud-workspace/config-repo
          clone-on-start: true
#  security:
#    user:
#      name: root
#      password: Telino_2018