spring:
  main:
    banner-mode: "off"
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/Dev/workspaces/cloud-workspace/SpringCloud/config-repo
          clone-on-start: true
  security:
    user:
      name: root
      password: Telino_2018

server:
  port: 8888
  
eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/